# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
  
source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'
source 'git@github.com:millicast/millicast-cocoapods-specs.git'
install! 'cocoapods', :deterministic_uuids => false
prepare_react_native_project!

production = ENV["PRODUCTION"] == "1"
linkage = ENV['USE_FRAMEWORKS']
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TestApp' do

  platform :ios, '14.0'
  $config = use_native_modules!
  use_react_native!(
    :path => $config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  target 'TestAppTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'TestApp-tvOS' do

  platform :tvos, '16.0'
  $config = use_native_modules!

  use_react_native!(
    :path => $config[:reactNativePath],
    :app_path => "#{Dir.pwd}/.."
  )

  target 'TestApp-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'TVOS_DEPLOYMENT_TARGET'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||=['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
    end
  end
   # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    $config[:reactNativePath],
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )
end
