name: CD iOS build and distribution

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  iOS-App-Build:
    runs-on: macos-13
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install modules
        run: yarn install
      - name: Temp update dependency for webrtc
        env:
          TEMP_IOS_DEPENDENCIES: ${{secrets.TEMP_IOS_DEPENDENCIES}}
        run: |
          cd node_modules/react-native-webrtc
          rm react-native-webrtc.podspec
          echo $TEMP_IOS_DEPENDENCIES > react-native-webrtc.podspec

      - name: Pod install
        run: cd ios && pod install
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64_APPSTORE }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD_APPSTORE }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_INTERACTIVE_PLAYER_PROFILE_BASE64_APPSTORE }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Create internal environment
        env:
          ENV: ${{secrets.ENV}}
        run: |
          echo $ENV > .env

      - name: Build iOS app
        run: cd ios && xcodebuild build -workspace TestApp.xcworkspace -scheme TestApp clean archive -archivePath "Actions"
